disableSerialization;
closeDialog 8457;
createDialog"XM8ViewRules";
ExileClientXM8IsPowerOn = true;
_display = findDisplay 8458;
_ctrl = _display displayCtrl 4007;
_ctrl ctrlSetStructuredText parseText (format["<t shadow='1' shadowColor='#000000' size='2' color='#FF0000' align='center'>SERVER RULES</t>"]);
_ctrl = _display displayCtrl 40071;
_ctrl ctrlSetStructuredText parseText (format["<img align='right' size='3'  shadowColor='#000000' image='\exile_assets\texture\ui\xm8_app_territory_ca.paa'/>"]);
_ctrl = _display displayCtrl 4022;
_ctrl ctrlSetStructuredText parseText (format["<t align='left'>1. No Camping Trader Cities!</t>"]);
_ctrl = _display displayCtrl 4023;
_ctrl ctrlSetStructuredText parseText (format["<t align='left'>2. No Shooting into Trader Cities!</t>"]);
_ctrl = _display displayCtrl 4024;
_ctrl ctrlSetStructuredText parseText (format["<t align='left'>3. No Building within 1000M of Trader Cities.</t>"]);
_ctrl = _display displayCtrl 4025;
_ctrl ctrlSetStructuredText parseText (format["<t align='left'>4. No Steeling from others within Trader Cities.</t>"]);
_ctrl = _display displayCtrl 4026;
_ctrl ctrlSetStructuredText parseText (format["<t align='left'>5. No Blocking High Traffic Loot Areas.</t>"]);
_ctrl = _display displayCtrl 4027;
_ctrl ctrlSetStructuredText parseText (format["<t align='left'>6. No Kamikaze into Player Bases!</t>"]);
_ctrl = _display displayCtrl 4028;
_ctrl ctrlSetStructuredText parseText (format["<t align='left'>7. No Lift and Tow Bombing!</t>"]);
_ctrl = _display displayCtrl 4029;
_ctrl ctrlSetStructuredText parseText (format["<t align='left'></t>"]);
_ctrl = _display displayCtrl 4030;
_ctrl ctrlSetStructuredText parseText (format["<t align='left'>Teamspeak: ts.mdbservers.net</t>"]);
_ctrl = _display displayCtrl 4031;
_ctrl ctrlSetStructuredText parseText (format["<t align='left'></t>"]);
_ctrl = _display displayCtrl 4032;
_ctrl ctrlSetStructuredText parseText (format["<t align='left'></t>"]);
_ctrl = _display displayCtrl 4033;
_ctrl ctrlSetStructuredText parseText (format["<t align='right'></t>"]);