disableSerialization;
closeDialog 8457;
createDialog"XM8ViewFAQ";
ExileClientXM8IsPowerOn = true;
_display = findDisplay 8458;
_ctrl = _display displayCtrl 4007;
_ctrl ctrlSetStructuredText parseText (format["<t shadow='1' shadowColor='#000000' size='2' color='#FF0000' align='center'>Server Tips</t>"]);
_ctrl = _display displayCtrl 40071;
_ctrl ctrlSetStructuredText parseText (format["<img align='right' size='3'  shadowColor='#000000' image='\exile_assets\texture\ui\xm8_app_territory_ca.paa'/>"]);
_ctrl = _display displayCtrl 4022;
_ctrl ctrlSetStructuredText parseText (format["<t align='left'>1. Don't logout wearing items you found off AI!</t>"]);
_ctrl = _display displayCtrl 4023;
_ctrl ctrlSetStructuredText parseText (format["<t align='left'>2. Remember to pay attention to the server restart warnings!</t>"]);
_ctrl = _display displayCtrl 4024;
_ctrl ctrlSetStructuredText parseText (format["<t align='left'>3. Vehicles that are not used within 3 days are lost!</t>"]);
_ctrl = _display displayCtrl 4025;
_ctrl ctrlSetStructuredText parseText (format["<t align='left'>4. Bases Decay after 7 days without maintenance dues being paid.</t>"]);
_ctrl = _display displayCtrl 4026;
_ctrl ctrlSetStructuredText parseText (format["<t align='left'>5. Helping other is what keeps a community strong!</t>"]);
_ctrl = _display displayCtrl 4027;
_ctrl ctrlSetStructuredText parseText (format["<t align='left'>6. Yes, this is a PvP Server.  Expect to die a lot to other players.</t>"]);
_ctrl = _display displayCtrl 4028;
_ctrl ctrlSetStructuredText parseText (format["<t align='left'>7. Yes, our admins do enjoy playing on our own server.  Requires login for hacks!</t>"]);
_ctrl = _display displayCtrl 4029;
_ctrl ctrlSetStructuredText parseText (format["<t align='left'>8. Each admin handles situations differently.  They are doing their best!</t>"]);
_ctrl = _display displayCtrl 4030;
_ctrl ctrlSetStructuredText parseText (format["<t align='left'>Teamspeak: ts.mdbservers.net</t>"]);
_ctrl = _display displayCtrl 4031;
_ctrl ctrlSetStructuredText parseText (format["<t align='left'></t>"]);
_ctrl = _display displayCtrl 4032;
_ctrl ctrlSetStructuredText parseText (format["<t align='left'></t>"]);
_ctrl = _display displayCtrl 4033;
_ctrl ctrlSetStructuredText parseText (format["<t align='right'></t>"]);